import type { SecurityToolDef } from '../_types'

export const SECURITY_TOOLS: SecurityToolDef[] = [
  {
    id: 'geobloqueo',
    name: 'Geobloqueo',
    description: 'Control de acceso por país usando Vercel Edge Network',
    cat: 'Control de Acceso',
    icon: 'Shield',
    status: 'active',
    configKey: 'geobloqueo',
  },
  {
    id: 'security_headers',
    name: 'Security Headers',
    description: 'Cabeceras HTTP de seguridad contra XSS, clickjacking y MITM',
    cat: 'Protección Web',
    icon: 'ShieldCheck',
    status: 'active',
    configKey: 'security_headers',
  },
  {
    id: 'rate_limiting',
    name: 'Rate Limiting',
    description: 'Límite de peticiones por IP para prevenir abusos',
    cat: 'Protección Web',
    icon: 'Gauge',
    status: 'active',
    configKey: 'rate_limiting',
  },
  {
    id: 'firewall',
    name: 'Firewall',
    description: 'Reglas de firewall personalizadas por ruta',
    cat: 'Protección Web',
    icon: 'Wall',
    status: 'coming_soon',
    configKey: 'firewall',
  },
  {
    id: 'access_logs',
    name: 'Logs de Acceso',
    description: 'Registro y monitoreo de intentos bloqueados en tiempo real',
    cat: 'Monitoreo',
    icon: 'ScrollText',
    status: 'active',
    configKey: 'access_logs',
  },
  {
    id: 'alerts',
    name: 'Alertas',
    description: 'Notificaciones ante intentos de acceso bloqueados',
    cat: 'Monitoreo',
    icon: 'Bell',
    status: 'coming_soon',
    configKey: 'alerts',
  },
]
