import type { SecurityToolDef } from '../_types'

export const SECURITY_TOOLS: SecurityToolDef[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    description: 'Centro de comando con KPIs, radar, gráficos y estado de herramientas',
    cat: 'Principal',
    icon: 'Cpu',
    status: 'active',
  },
  {
    id: 'geobloqueo',
    name: 'Geobloqueo',
    description: 'Control de acceso por país usando Vercel Edge Network',
    cat: 'Control de Acceso',
    icon: 'Shield',
    status: 'active',
    configKey: 'geobloqueo',
  },
  {
    id: 'security_headers',
    name: 'Security Headers',
    description: 'Cabeceras HTTP de seguridad contra XSS, clickjacking y MITM',
    cat: 'Protección Web',
    icon: 'ShieldCheck',
    status: 'active',
    configKey: 'security_headers',
  },
  {
    id: 'rate_limiting',
    name: 'Rate Limiting',
    description: 'Límite de peticiones por IP para prevenir abusos',
    cat: 'Protección Web',
    icon: 'Gauge',
    status: 'active',
    configKey: 'rate_limiting',
  },
  {
    id: 'firewall',
    name: 'Firewall',
    description: 'Reglas de firewall personalizadas por ruta',
    cat: 'Protección Web',
    icon: 'Wall',
    status: 'coming_soon',
    configKey: 'firewall',
  },
  {
    id: 'access_logs',
    name: 'Logs de Acceso',
    description: 'Registro y monitoreo de intentos bloqueados en tiempo real',
    cat: 'Monitoreo',
    icon: 'ScrollText',
    status: 'active',
    configKey: 'access_logs',
  },
  {
    id: 'bot_protection',
    name: 'Bot Protection',
    description: 'CAPTCHA invisible con Cloudflare Turnstile para formularios',
    cat: 'Protección Web',
    icon: 'Bot',
    status: 'active',
    configKey: 'bot_protection',
  },
  {
    id: 'alerts',
    name: 'Alertas',
    description: 'Detección de amenazas con radar, heat map y notificaciones',
    cat: 'Monitoreo',
    icon: 'Bell',
    status: 'active',
    configKey: 'alerts',
  },
  {
    id: 'scanner',
    name: 'AI Scanner',
    description: 'Escáner inteligente de código, cuentas, configuración y datos',
    cat: 'Monitoreo',
    icon: 'Search',
    status: 'active',
  },
  {
    id: 'login_geo',
    name: 'Login Geo',
    description: 'Detección de inicios de sesión desde ubicaciones inusuales',
    cat: 'Monitoreo',
    icon: 'Globe',
    status: 'active',
  },
]
