'use client';
import { useState, useRef, useEffect, useCallback, useMemo } from 'react';
import JSZip from 'jszip';
import { useEmailTemplates, useEmailPalettes } from '@/lib/hooks/useEmailTemplates';
import { useEmailSenders } from '@/lib/hooks/useEmailSenders';
import { useEmailMedia } from '@/lib/hooks/useEmailMedia';
import {
  SOCIAL_CONFIG, DEFAULT_PALETTES, INITIAL_SETTINGS, INITIAL_BLOCKS,
  PLATFORM_LABELS_MAP, MERCURY_MODULE_MAP, getUniqueId, getDefaultContent, RECEIPT_DEMO, FONTS, FONT_WEIGHTS, AVAILABLE_BLOCKS
} from '../_types';
import { generateHTML } from '../lib/htmlGenerator';

export function useMails() {
  const { getTemplates, getTemplate, saveTemplate: saveTemplateToDb, deleteTemplate: deleteTemplateFromDb, loading: templatesLoading } = useEmailTemplates();
  const { getPalettes: getPalettesFromDb, savePalette: savePaletteToDb, deletePalette: deletePaletteFromDb, loading: palettesLoading } = useEmailPalettes();
  const { senders, loading: sendersLoading, getSenders, saveSender, deleteSender } = useEmailSenders();
  const { media, loading: mediaLoading, getMedia, uploadMedia, deleteMedia } = useEmailMedia();

  const [templates, setTemplates] = useState([]);
  const [currentTemplateId, setCurrentTemplateId] = useState(null);
  const [blocks, setBlocks] = useState([]);
  const [settings, setSettings] = useState(INITIAL_SETTINGS);
  const [selectedBlockId, setSelectedBlockId] = useState(null);
  const [previewMode, setPreviewMode] = useState('desktop');
  const [activeTab, setActiveTab] = useState('blocks');
  const [demoData, setDemoData] = useState({ nombre: 'Juan Pérez', email: 'juan@email.com', password: 'Blis2024X', telefono: '+51 999 888 777', productos: '✅ Masterclass Inteligencia Competitiva\n✅ Kit Legal de Agentes\n✅ Ebook: Técnicas de Cierre', total: '338.00', metodo_pago: 'Tarjeta de Crédito', fecha: new Date().toLocaleDateString('es-PE', { day: '2-digit', month: 'long', year: 'numeric' }), empresa: 'BLIS Corp', ciudad: 'Lima', campana: 'Oferta Black Friday', descuento: '40%', cupon: 'BLIS40', vencimiento: '31 de diciembre 2025', enlace_acceso: 'https://blis-corp.com/miembros', enlace_baja: 'https://blis-corp.com/baja', whatsapp: '+51 999 000 111', subtotal: '367.00', descuento_monto: '29.00', 'respuesta-de-correo': 'Gracias por contactarnos. Hemos recibido tu solicitud y te responderemos a la brevedad.' });
  const [previewWithDemo, setPreviewWithDemo] = useState(false);
  const [theme, setTheme] = useState('dark');
  const [zipModal, setZipModal] = useState(false);
  const [zipFiles, setZipFiles] = useState([]);
  const [zipLoading, setZipLoading] = useState(false);
  const [envatoStatus, setEnvatoStatus] = useState(null);
  const [envatoQuery, setEnvatoQuery] = useState('email template');
  const [envatoResults, setEnvatoResults] = useState([]);
  const [envatoLoading, setEnvatoLoading] = useState(false);
  const [envatoDownloading, setEnvatoDownloading] = useState(null);
  const [envatoNeedsSession, setEnvatoNeedsSession] = useState(false);
  const [leftPanelTab, setLeftPanelTab] = useState('blocks');
  const [isEditingPalette, setIsEditingPalette] = useState(false);
  const [editingPaletteId, setEditingPaletteId] = useState(null);
  const [paletteForm, setPaletteForm] = useState({ name: 'Nueva Paleta', bodyBg: '#0a0a0a', containerBg: '#111111', text: '#e5e7eb', primary: '#e11d48' });
  const [showExportHtml, setShowExportHtml] = useState(false);
  const [showSendModal, setShowSendModal] = useState(false);
  const [showSettingsModal, setShowSettingsModal] = useState(false);
  const [settingsTab, setSettingsTab] = useState('senders');
  const [sendTab, setSendTab] = useState('destinatarios');
  const [campaignConfig, setCampaignConfig] = useState({ subject: '', preview: '', type: 'manual', emails: '', selectedSenderId: '' });
  const [attachments, setAttachments] = useState([]);
  const [editingSender, setEditingSender] = useState(null);
  const [testingConnection, setTestingConnection] = useState(false);
  const [testResult, setTestResult] = useState(null);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [saveAsNew, setSaveAsNew] = useState(false);
  const [showTemplatesModal, setShowTemplatesModal] = useState(false);
  const [showMediaModal, setShowMediaModal] = useState(false);
  const mediaCallbackRef = useRef(null);
  const [mediaTab, setMediaTab] = useState('all');
  const [templateName, setTemplateName] = useState('');
  const [savedTemplates, setSavedTemplates] = useState([]);
  const [copied, setCopied] = useState(false);
  const fileInputRef = useRef(null);
  const mediaUploadRef = useRef(null);

  useEffect(() => { if (theme === 'dark') document.documentElement.classList.add('dark'); else document.documentElement.classList.remove('dark'); }, [theme]);
  useEffect(() => { const load = async () => { const t = await getTemplates(); if (t) setSavedTemplates(t); }; load(); }, []);
  useEffect(() => { getSenders(); }, [getSenders]);
  useEffect(() => { getMedia(); }, [getMedia]);
  useEffect(() => { const loadPalettes = async () => { const dbPalettes = await getPalettesFromDb(); if (dbPalettes && dbPalettes.length > 0) { const mapped = dbPalettes.map(p => ({ id: p.id, name: p.nombre, bodyBg: p.body_bg, containerBg: p.container_bg, text: p.text, primary: p.primary_color })); setSettings(prev => ({ ...prev, palettes: [...DEFAULT_PALETTES, ...mapped.filter(dp => !DEFAULT_PALETTES.some(dp2 => dp2.id === dp.id))] })); } }; loadPalettes(); }, []);
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get('envato_connected')) { setLeftPanelTab('envato'); checkEnvatoStatus(); window.history.replaceState({}, '', window.location.pathname); } if (params.get('envato_error')) { alert('Error al conectar con Envato: ' + params.get('envato_error')); window.history.replaceState({}, '', window.location.pathname); } }, []);

  useEffect(() => { if (typeof window !== 'undefined' && currentTemplateId) { try { localStorage.setItem('blismail_currentTemplateId', currentTemplateId); } catch {} } }, [currentTemplateId]);

  useEffect(() => { const autoLoad = async () => { try { const storedId = typeof window !== 'undefined' ? localStorage.getItem('blismail_currentTemplateId') : null; if (storedId && !currentTemplateId) { const found = await getTemplate(storedId); if (found) { const blks = typeof found.blocks === 'string' ? JSON.parse(found.blocks) : found.blocks; const sets = typeof found.settings === 'string' ? JSON.parse(found.settings) : found.settings; setBlocks(blks || []); setSettings(sets || INITIAL_SETTINGS); setCurrentTemplateId(found.id); setTemplateName(found.nombre); } else { try { localStorage.removeItem('blismail_currentTemplateId'); } catch {} } } } catch {} }; autoLoad(); }, []);

  const currentPalettes = settings.palettes && settings.palettes.length > 0 ? settings.palettes : DEFAULT_PALETTES;
  const activePalette = currentPalettes.find(p => p.id === settings.activePaletteId) || currentPalettes[0] || DEFAULT_PALETTES[0];

  const findBlockInfo = (blocksArray, id, parentId = null, colIndex = null) => { for (let i = 0; i < blocksArray.length; i++) { if (blocksArray[i].id === id) return { block: blocksArray[i], parentId, colIndex, index: i, array: blocksArray }; if (blocksArray[i].type === 'columns') { for (let j = 0; j < blocksArray[i].content.cols.length; j++) { const found = findBlockInfo(blocksArray[i].content.cols[j], id, blocksArray[i].id, j); if (found) return found; } } } return null; };

  const addBlock = (type) => { const newBlock = { id: getUniqueId(type), type, content: getDefaultContent(type, activePalette) }; const info = selectedBlockId ? findBlockInfo(blocks, selectedBlockId) : null; if (info && info.parentId) setBlocks(updateBlockTree(blocks, info.parentId, 'add_to_col', { colIndex: info.colIndex, newBlock, insertAfter: info.index })); else setBlocks([...blocks, newBlock]); setSelectedBlockId(newBlock.id); setActiveTab('blocks'); };
  const addBlockToSpecificColumn = (parentId, colIndex, type) => { const newBlock = { id: getUniqueId(type), type, content: getDefaultContent(type, activePalette) }; setBlocks(updateBlockTree(blocks, parentId, 'append_to_col', { colIndex, newBlock })); setSelectedBlockId(newBlock.id); };

  const updateBlockTree = (currentBlocks, targetId, action, payload) => { const newBlocks = [...currentBlocks]; for (let i = 0; i < newBlocks.length; i++) { if (newBlocks[i].id === targetId) { if (action === 'update_content') newBlocks[i] = { ...newBlocks[i], content: { ...newBlocks[i].content, [payload.key]: payload.value } }; else if (action === 'append_to_col') { const newCols = [...newBlocks[i].content.cols]; newCols[payload.colIndex] = [...newCols[payload.colIndex], payload.newBlock]; newBlocks[i] = { ...newBlocks[i], content: { ...newBlocks[i].content, cols: newCols } }; } else if (action === 'add_to_col') { const newCols = [...newBlocks[i].content.cols]; newCols[payload.colIndex].splice(payload.insertAfter + 1, 0, payload.newBlock); newBlocks[i] = { ...newBlocks[i], content: { ...newBlocks[i].content, cols: newCols } }; } return newBlocks; } if (newBlocks[i].type === 'columns') { const updatedCols = newBlocks[i].content.cols.map(col => updateBlockTree(col, targetId, action, payload)); newBlocks[i] = { ...newBlocks[i], content: { ...newBlocks[i].content, cols: updatedCols } }; } } return newBlocks; };

  const handleUpdateContent = useCallback((key, value) => { if (!selectedBlockId) return; setBlocks(prev => { const updateRecursive = (arr) => arr.map(b => { if (b.id === selectedBlockId) return { ...b, content: { ...b.content, [key]: value } }; if (b.type === 'columns') return { ...b, content: { ...b.content, cols: b.content.cols.map(c => updateRecursive(c)) } }; return b; }); return updateRecursive(prev); }); }, [selectedBlockId]);
  const updateSetting = useCallback((key, value) => { setSettings(prev => ({ ...prev, [key]: value })); }, []);
  const removeBlock = useCallback((id, e) => { if (e) e.stopPropagation(); setBlocks(prev => { const removeRecursive = (arr) => arr.filter(b => b.id !== id).map(b => { if (b.type === 'columns') return { ...b, content: { ...b.content, cols: b.content.cols.map(c => removeRecursive(c)) } }; return b; }); return removeRecursive(prev); }); setSelectedBlockId(prev => prev === id ? null : prev); }, []);
  const duplicateBlock = useCallback((id, e) => { if (e) e.stopPropagation(); const info = findBlockInfo(blocks, id); if (!info) return; const newId = getUniqueId(info.block.type); const cloned = JSON.parse(JSON.stringify({ ...info.block, id: newId })); setBlocks(prev => { if (info.parentId === null) { const newArr = [...prev]; newArr.splice(info.index + 1, 0, cloned); return newArr; } const updateParent = (currBlocks) => currBlocks.map(b => { if (b.id === info.parentId) { const newCols = [...b.content.cols]; newCols[info.colIndex] = [...newCols[info.colIndex]]; newCols[info.colIndex].splice(info.index + 1, 0, cloned); return { ...b, content: { ...b.content, cols: newCols } }; } if (b.type === 'columns') return { ...b, content: { ...b.content, cols: b.content.cols.map(c => updateParent(c)) } }; return b; }); return updateParent(prev); }); setSelectedBlockId(newId); }, [blocks]);
  const moveBlock = useCallback((id, direction, e) => { if (e) e.stopPropagation(); setBlocks(prev => { const info = findBlockInfo(prev, id); if (!info) return prev; const moveInArray = (arr, idx, dir) => { const newArr = [...arr]; if (dir === 'up' && idx > 0) [newArr[idx - 1], newArr[idx]] = [newArr[idx], newArr[idx - 1]]; if (dir === 'down' && idx < arr.length - 1) [newArr[idx + 1], newArr[idx]] = [newArr[idx], newArr[idx + 1]]; return newArr; }; if (info.parentId === null) return moveInArray(prev, info.index, direction); const updateParentCol = (currBlocks) => currBlocks.map(b => { if (b.id === info.parentId) { const newCols = [...b.content.cols]; newCols[info.colIndex] = moveInArray(newCols[info.colIndex], info.index, direction); return { ...b, content: { ...b.content, cols: newCols } }; } if (b.type === 'columns') return { ...b, content: { ...b.content, cols: b.content.cols.map(c => updateParentCol(c)) } }; return b; }); return updateParentCol(prev); }); }, [blocks]);

  const toggleCreatePalette = () => { if (isEditingPalette && !editingPaletteId) setIsEditingPalette(false); else { setEditingPaletteId(null); setPaletteForm({ name: 'Nueva Paleta', bodyBg: '#0a0a0a', containerBg: '#111111', text: '#e5e7eb', primary: '#e11d48' }); setIsEditingPalette(true); } };
  const startEditPalette = (palette, e) => { e.stopPropagation(); setEditingPaletteId(palette.id); setPaletteForm({ ...palette }); setIsEditingPalette(true); };
  const deletePalette = async (id, e) => { e.stopPropagation(); if (currentPalettes.length <= 1) { alert("No puedes eliminar la última paleta."); return; } const newPalettes = currentPalettes.filter(p => p.id !== id); setSettings(prev => ({ ...prev, palettes: newPalettes })); if (settings.activePaletteId === id) applyPalette(newPalettes[0].id, newPalettes[0]); if (editingPaletteId === id) setIsEditingPalette(false); if (!id.startsWith('bliscorp-')) await deletePaletteFromDb(id); };
  const movePalette = (index, dir, e) => { e.stopPropagation(); const newPalettes = [...currentPalettes]; if (dir === 'up' && index > 0) [newPalettes[index - 1], newPalettes[index]] = [newPalettes[index], newPalettes[index - 1]]; else if (dir === 'down' && index < newPalettes.length - 1) [newPalettes[index + 1], newPalettes[index]] = [newPalettes[index], newPalettes[index + 1]]; setSettings(prev => ({ ...prev, palettes: newPalettes })); };
  const applyPalette = (paletteId, explicitPaletteObj = null) => { const p = explicitPaletteObj || currentPalettes.find(x => x.id === paletteId); if (!p) return; const old = currentPalettes.find(pa => pa.id === settings.activePaletteId) || currentPalettes[0]; setSettings(prev => ({ ...prev, activePaletteId: p.id, bodyBg: p.bodyBg, containerBg: p.containerBg })); const updateColors = (arr) => arr.map(b => { let c = { ...b.content }; if (c.textColor && c.textColor.toLowerCase() === old.text.toLowerCase()) c.textColor = p.text; if (b.type === 'button') { if (c.buttonBgColor && c.buttonBgColor.toLowerCase() === old.primary.toLowerCase()) c.buttonBgColor = p.primary; if (c.borderColor && c.borderColor.toLowerCase() === old.primary.toLowerCase()) c.borderColor = p.primary; } if (b.type === 'columns') c.cols = c.cols.map(colArr => updateColors(colArr)); return { ...b, content: c }; }); setBlocks(prev => updateColors(prev)); };
  const savePalette = () => { if (editingPaletteId) { const updated = { ...paletteForm, id: editingPaletteId }; setSettings(prev => ({ ...prev, palettes: prev.palettes.map(p => p.id === editingPaletteId ? updated : p) })); applyPalette(editingPaletteId, updated); savePaletteToDb({ id: editingPaletteId, nombre: paletteForm.name, body_bg: paletteForm.bodyBg, container_bg: paletteForm.containerBg, text: paletteForm.text, primary_color: paletteForm.primary }); } else { const newId = `palette-${Date.now()}`; const pal = { ...paletteForm, id: newId }; setSettings(prev => ({ ...prev, palettes: [...(prev.palettes || []), pal] })); applyPalette(newId, pal); savePaletteToDb({ nombre: paletteForm.name, body_bg: paletteForm.bodyBg, container_bg: paletteForm.containerBg, text: paletteForm.text, primary_color: paletteForm.primary }); } setIsEditingPalette(false); };
  const saveTemplate = async (nombre = 'Nueva Plantilla', isNew = true) => { const templateId = isNew ? undefined : (currentTemplateId || (typeof window !== 'undefined' ? localStorage.getItem('blismail_currentTemplateId') : null)); if (!isNew && !templateId) { alert('Error: No se pudo identificar la plantilla a actualizar. Carga la plantilla nuevamente.'); return null; } const saved = await saveTemplateToDb({ id: templateId, nombre, settings, blocks }); if (saved) { setCurrentTemplateId(saved.id); alert(isNew ? 'Plantilla guardada correctamente' : 'Plantilla actualizada correctamente'); return saved; } return null; };
  const handleSaveTemplate = async (isNew = true) => { if (isNew && !templateName.trim()) { alert('Por favor ingresa un nombre'); return; } const nameToSave = isNew ? templateName : (templateName || savedTemplates.find(t => t.id === currentTemplateId)?.nombre || 'Plantilla existente'); const saved = await saveTemplate(nameToSave, isNew); if (saved) { setShowSaveModal(false); setSaveAsNew(false); setTemplateName(nameToSave); const t = await getTemplates(); if (t) setSavedTemplates(t); } };
  const handleLoadTemplate = async (templateId) => { try { const found = await getTemplate(templateId); if (found) { const blks = typeof found.blocks === 'string' ? JSON.parse(found.blocks) : found.blocks; const sets = typeof found.settings === 'string' ? JSON.parse(found.settings) : found.settings; setBlocks(blks || []); setSettings(sets || INITIAL_SETTINGS); setCurrentTemplateId(found.id); setTemplateName(found.nombre); setShowTemplatesModal(false); setSelectedBlockId(null); if ((blks || []).some(b => b.type === 'receipt')) setPreviewWithDemo(true); } else alert("No se pudo cargar la plantilla."); } catch (e) { console.error(e); alert("Error al cargar la plantilla."); } };
  const handleNewTemplate = () => { setBlocks([]); setSettings(INITIAL_SETTINGS); setCurrentTemplateId(null); setTemplateName(''); setSelectedBlockId(null); try { localStorage.removeItem('blismail_currentTemplateId'); } catch {} };
  const handleSaveAsNew = () => { setTemplateName(''); setSaveAsNew(true); setShowSaveModal(true); };
  const handleDeleteTemplate = async (templateId) => {
    const ok = await deleteTemplateFromDb(templateId);
    if (ok) {
      const t = await getTemplates();
      if (t) setSavedTemplates(t);
    }
  };
  const handleOpenSendModal = () => { setCampaignConfig(prev => ({ ...prev, selectedSenderId: settings?.senderId || prev.selectedSenderId, subject: settings?.subject || prev.subject, preview: settings?.previewText || prev.preview })); setShowSendModal(true); };
  const handleSendCampaign = async () => { setSendingEmail(true); try { const sender = senders?.find(s => s.id === campaignConfig.selectedSenderId); if (!sender) { alert("Selecciona un remitente"); setSendingEmail(false); return; } const emails = campaignConfig.type === 'manual' ? (campaignConfig.emails || '').split(',').map(e => e.trim()).filter(Boolean) : []; if (emails.length === 0 && campaignConfig.type === 'manual') { alert("Ingresa al menos un correo"); setSendingEmail(false); return; } const htmlContent = generateHTML(displayBlocks, settings); const attachData = []; for (const file of attachments) { const dataUrl = await new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); }); attachData.push({ filename: file.name, content: String(dataUrl).split(',')[1], encoding: 'base64' }); } const res = await fetch('/api/send-email', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ senderId: sender.id, to: emails, subject: campaignConfig.subject || settings?.subject || 'Sin asunto', html: htmlContent, previewText: campaignConfig.preview || settings?.previewText || '', attachments: attachData }) }); const data = await res.json(); if (data.success) { alert(`Enviado a ${data.sent || emails.length} destinatarios`); setShowSendModal(false); setAttachments([]); } else { alert("Error: " + (data.error || "Desconocido")); } } catch (e) { alert("Error al enviar: " + e.message); } setSendingEmail(false); };
  const exportTemplate = () => { const d = JSON.stringify({ settings, blocks }, null, 2); const b = new Blob([d], { type: 'application/json' }); const u = URL.createObjectURL(b); const a = document.createElement('a'); a.href = u; a.download = `plantilla-bliscorp-${Date.now()}.json`; document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(u); };
  const handleNetworkUpdate = (netId, key, value) => { const selBlock = findBlockInfo(blocks, selectedBlockId)?.block; if (!selBlock) return; let newNets; if (typeof key === 'object') newNets = selBlock.content.networks.map(n => n.id === netId ? { ...n, ...key } : n); else newNets = selBlock.content.networks.map(n => n.id === netId ? { ...n, [key]: value } : n); handleUpdateContent('networks', newNets); };
  const addNetwork = () => { const selBlock = findBlockInfo(blocks, selectedBlockId)?.block; if (!selBlock) return; handleUpdateContent('networks', [...selBlock.content.networks, { id: `net-${Date.now()}`, network: 'facebook', url: 'https://', iconColor: '#ffffff', bgColor: '#1877F2' }]); };
  const applyDemoData = (html) => { let r = html; Object.entries(demoData).forEach(([k, v]) => { r = r.replaceAll(`{{${k}}}`, v); }); return r; };
  const applyDemoToBlocks = (blocksList) => { const allDemo = { ...demoData, ...RECEIPT_DEMO }; const replaceVars = (str) => { if (typeof str !== 'string') return str; let r = str; Object.entries(allDemo).forEach(([k, v]) => { r = r.replaceAll(`{{${k}}}`, v); }); return r; }; const processBlock = (b) => { const nc = { ...b.content }; if (nc.text) nc.text = replaceVars(nc.text); if (nc.src) nc.src = replaceVars(nc.src); if (nc.link) nc.link = replaceVars(nc.link); if (b.type === 'receipt') { nc.items = (nc.items || []).map((item, i) => ({ ...item, nombre: replaceVars(item.nombre), categoria: replaceVars(item.categoria), precio: replaceVars(item.precio), imagen: item.imagen || replaceVars(`{{producto_${i+1}_imagen}}`) })); nc.subtotalVar = replaceVars(nc.subtotalVar || '{{subtotal}}'); nc.descuentoVar = replaceVars(nc.descuentoVar || '{{descuento_monto}}'); nc.cuponVar = replaceVars(nc.cuponVar || '{{cupon}}'); nc.totalVar = replaceVars(nc.totalVar || '{{total}}'); nc.metodoPagoVar = replaceVars(nc.metodoPagoVar || '{{metodo_pago}}'); nc.fechaVar = replaceVars(nc.fechaVar || '{{fecha}}'); } if (nc.cols) nc.cols = nc.cols.map(col => Array.isArray(col) ? col.map(processBlock) : col); return { ...b, content: nc }; }; return blocksList.map(processBlock); };

  const importTemplate = (e) => { const file = e.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = (event) => { try { const data = JSON.parse(event.target.result); if (data.blocks && data.settings) { setBlocks(data.blocks); setSettings(data.settings); setSelectedBlockId(null); } else alert('Formato incorrecto.'); } catch (err) { alert('Error al importar.'); } }; reader.readAsText(file); e.target.value = null; };

  const checkEnvatoStatus = async () => { try { const res = await fetch('/api/envato/status'); const data = await res.json(); setEnvatoStatus(data); } catch { setEnvatoStatus({ connected: false }); } };
  const searchEnvato = async (q) => { setEnvatoLoading(true); setEnvatoResults([]); setEnvatoNeedsSession(false); try { const res = await fetch(`/api/envato/elements?q=${encodeURIComponent(q)}&page=1`); const data = await res.json(); if (data.success) setEnvatoResults(data.results || []); else if (data.needsSession) setEnvatoNeedsSession(true); else console.error('Elements error:', data.error); } catch (err) { console.error('Elements search error:', err); } setEnvatoLoading(false); };
  const pasteEnvatoSession = async () => { const cookie = prompt('📋 Cómo obtener las cookies:\n\n1. Ve a https://app.envato.com e inicia sesión\n2. Presiona F12 → tab "Network"\n3. Recarga la página (F5)\n4. Clic en cualquier request a app.envato.com\n5. En "Request Headers" copia el valor de "Cookie:"\n\nPega aquí ese valor:'); if (!cookie?.trim()) return; const res = await fetch('/api/envato/set-session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session: cookie.trim() }), }); const data = await res.json(); if (data.success) { setEnvatoNeedsSession(false); searchEnvato(envatoQuery); } else alert('Error: ' + data.error); };
  const downloadEnvatoItem = async (item) => { setEnvatoDownloading(item.id); try { const endpoint = item.isElements ? '/api/envato/elements-download' : '/api/envato/download'; const body = item.isElements ? { item_slug: item.slug || String(item.id), item_url: item.url } : { item_id: String(item.id || item.envatoId || '').replace(/^envato-/i, '') }; const res = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await res.json(); if (!data.success) { if (data.needsCredentials) alert('Credenciales no configuradas'); else { const goManual = window.confirm(`⚠️ ${data.error}\n\n¿Abrir el item en Envato para descargarlo manualmente?`); if (goManual) window.open(item.url || 'https://elements.envato.com/email-templates', '_blank'); } setEnvatoDownloading(null); return; } if (data.htmlFiles?.length > 0) { if (data.htmlFiles.length === 1) importFromHTML(data.htmlFiles[0].htmlContent, data.htmlFiles[0].platformLabel); else setZipFiles(data.htmlFiles); } else alert('No se encontraron plantillas HTML.'); } catch (err) { alert('Error: ' + err.message); } setEnvatoDownloading(null); };

  const processZipFile = async (file) => { setZipLoading(true); try { const zip = new JSZip(); const contents = await zip.loadAsync(file); const imageMap = {}; const imageExts = ['.jpg','.jpeg','.png','.gif','.svg','.webp']; await Promise.all(Object.entries(contents.files).map(async ([path, entry]) => { if (entry.dir) return; if (!imageExts.some(ext => path.toLowerCase().endsWith(ext))) return; try { const blob = await entry.async('blob'); const ext = path.toLowerCase().split('.').pop(); const mimeMap = { jpg:'image/jpeg', jpeg:'image/jpeg', png:'image/png', gif:'image/gif', svg:'image/svg+xml', webp:'image/webp' }; const dataUrl = await new Promise(resolve => { const reader = new FileReader(); reader.onload = e => resolve(e.target.result); reader.readAsDataURL(new Blob([blob], { type: mimeMap[ext] || 'image/png' })); }); const filename = path.split('/').pop(); imageMap[path] = dataUrl; imageMap[filename] = dataUrl; imageMap['images/' + filename] = dataUrl; } catch {} }));
      const imageByFilename = {}; Object.entries(imageMap).forEach(([p, d]) => { const fn = p.split('/').pop(); if (!imageByFilename[fn]) imageByFilename[fn] = d; });
      const resolveImage = (src) => { if (!src || src.startsWith('http') || src.startsWith('data:') || src.startsWith('//') || src.startsWith('mailto:') || src === '#' || src.startsWith('cid:')) return null; const clean = src.replace(/^(\.\.\/)+/, '').replace(/^\.\//, ''); const fn = clean.split('/').pop(); if (!fn || fn === '') return null; return imageMap[src] || imageMap[clean] || imageMap[fn] || imageByFilename[fn] || null; };
      const fixImages = (html) => html.replace(/src=["']([^"']+)["']/gi, (m, src) => { const r = resolveImage(src); if (r) return `src="${r}"`; if (!src.startsWith('http') && !src.startsWith('data:') && !src.startsWith('//') && !src.startsWith('#')) { const fn = src.split('/').pop(); return `src="https://placehold.co/600x200/1a1a1a/444?text=${encodeURIComponent(fn || 'img')}"`; } return m; }).replace(/background=["']([^"']+)["']/gi, (m, src) => { const r = resolveImage(src); return r ? `background="${r}"` : m; }).replace(/url\(['"]?([^'")]+)['"]?\)/gi, (m, src) => { const r = resolveImage(src); return r ? `url("${r}")` : m; });
      const htmlEntries = Object.entries(contents.files).filter(([p, e]) => { if (e.dir) return false; if (!p.toLowerCase().endsWith('.html')) return false; const lower = p.toLowerCase(); const parts = lower.split('/'); if (parts.some(part => ['documentation', 'docs', 'doc', 'readme', 'guide', 'help', 'open-this-folder-first'].includes(part))) return false; return true; }).sort(([a], [b]) => a.localeCompare(b));
      if (htmlEntries.length === 0) { alert('No se encontraron HTML.'); setZipLoading(false); return; }
      const processed = await Promise.all(htmlEntries.map(async ([path, entry]) => { const raw = await entry.async('string'); const htmlContent = fixImages(raw); const platform = detectEnvatoPlatform(htmlContent); const filename = path.split('/').pop().replace('.html',''); const pathLower = path.toLowerCase(); const PLATFORM_KEYWORDS = ['mailchimp', 'mail-chimp', 'campaign-monitor', 'campaignmonitor', 'stampready', 'stamp-ready', 'sendgrid', 'freshmail', 'activecampaign', 'mymail', 'icontact']; const isPlatformVariant = PLATFORM_KEYWORDS.some(kw => pathLower.includes(kw)); const isIndex = filename.toLowerCase() === 'index' || filename.toLowerCase().includes('index'); const parts = path.split('/').filter(Boolean); const folder = parts.length > 1 ? parts[parts.length - 2] : 'Principal'; return { path, name: filename, folder, htmlContent, platform, platformLabel: PLATFORM_LABELS_MAP[platform] || 'HTML Genérico', isPlatformVariant, isIndex, previewHtml: htmlContent }; }));
      const SKIP_NAMES = ['stampready', 'stamp-ready', 'mailchimp', 'mail-chimp', 'campaign-monitor', 'campaignmonitor', 'mymail', 'sendgrid', 'freshmail', 'activecampaign', 'icontact'];
      const platformFiles = processed.filter(f => SKIP_NAMES.some(s => f.name.toLowerCase().includes(s)) || f.isPlatformVariant);
      const genericFiles = processed.filter(f => !SKIP_NAMES.some(s => f.name.toLowerCase().includes(s)) && !f.isPlatformVariant);
      const RAW_NAMES = ['raw', 'index', 'main', 'email', 'template', 'newsletter'];
      const autoSelect = genericFiles.find(f => f.name.toLowerCase() === 'raw') || genericFiles.find(f => RAW_NAMES.includes(f.name.toLowerCase())) || genericFiles.find(f => f.platform === 'generic') || genericFiles[0];
      if (autoSelect && genericFiles.length <= 2 && platformFiles.length > 0) { importFromHTML(autoSelect.htmlContent, autoSelect.platformLabel); setZipLoading(false); return; }
      const byPlatform = {}; processed.forEach(f => { const key = f.isPlatformVariant ? f.platform : 'generic_' + f.name; if (!byPlatform[key]) byPlatform[key] = []; byPlatform[key].push(f); });
      const toShow = Object.values(byPlatform).map(group => ({ ...group[0], variantCount: group.length, allVariants: group }));
      if (toShow.length === 1) { importFromHTML(toShow[0].htmlContent, toShow[0].platformLabel); } else { const recommended = toShow.find(f => f.name.toLowerCase() === 'raw') || toShow.find(f => f.name.toLowerCase().includes('-html')) || toShow.find(f => f.platform === 'generic' && !f.name.toLowerCase().includes('index')) || toShow.find(f => f.platform === 'generic') || toShow[0]; if (recommended) recommended.isRecommended = true; const sorted = [...toShow.filter(f => f.isRecommended), ...toShow.filter(f => !f.isRecommended && !f.name.toLowerCase().includes('index')), ...toShow.filter(f => f.name.toLowerCase().includes('index'))]; setZipFiles(sorted); setZipModal(true); }
    } catch (err) { console.error('Error ZIP:', err); alert('Error al procesar el ZIP.'); } setZipLoading(false); };

  const detectEnvatoPlatform = (htmlString) => { const h = htmlString.toLowerCase(); if (h.includes('mc:edit') || h.includes('mc:repeatable') || h.includes('mailchimp')) return 'mailchimp'; if (h.includes('stampready') || h.includes('stamp-ready') || h.includes('sr:')) return 'stampready'; if (h.includes('campaign monitor') || h.includes('campaignmonitor') || h.includes('cm:') || h.includes('editable')) return 'campaignmonitor'; if (h.includes('sendgrid')) return 'sendgrid'; if (h.includes('freshmail')) return 'freshmail'; if (h.includes('activecampaign')) return 'activecampaign'; if (h.includes('mymail') || h.includes('my-mail')) return 'mymail'; if (h.includes('icontact')) return 'icontact'; return 'generic'; };

  const importFromHTML = (htmlContent, platformLabel) => { try { const parsed = parseEnvatoHTML(htmlContent); if (parsed && parsed.length > 0) { setBlocks(parsed); setSelectedBlockId(null); setActiveTab('blocks'); setZipModal(false); } else { const bodyMatch = htmlContent.match(/<body[^>]*>([\s\S]*?)<\/body>/i); const bodyContent = bodyMatch ? bodyMatch[1] : htmlContent; setBlocks([{ id: getUniqueId('html'), type: 'html', content: { ...getDefaultContent('html', activePalette), code: bodyContent } }]); setSelectedBlockId(null); setActiveTab('blocks'); setZipModal(false); } } catch (err) { console.error('importFromHTML error:', err); alert('Error al procesar: ' + err.message); } };

  // Parser functions - these are pure functions that parse HTML into blocks
  const preprocessHTML = (htmlString, platform) => { let html = htmlString; switch (platform) { case 'mailchimp': html = html.replace(/mc:edit="[^"]*"/gi, ''); html = html.replace(/mc:repeatable="[^"]*"/gi, ''); html = html.replace(/mc:hideable="[^"]*"/gi, ''); html = html.replace(/mc:variant="[^"]*"/gi, ''); html = html.replace(/\*\|([^|]+)\|\*/g, '{{$1}}'); break; case 'stampready': html = html.replace(/sr:[a-z-]+="[^"]*"/gi, ''); html = html.replace(/data-sr-[a-z-]+="[^"]*"/gi, ''); break; case 'campaignmonitor': html = html.replace(/ editable(?=[\s>])/gi, ''); html = html.replace(/ label="[^"]*"/gi, ''); break; } html = html.replace(/<!--\[if[^\]]*\]>[\s\S]*?<!\[endif\]-->/gi, ''); return html; };

  const parseEnvatoHTML = (htmlString) => { const platform = detectEnvatoPlatform(htmlString); const cleanedHTML = preprocessHTML(htmlString, platform); const moduleMatches = cleanedHTML.match(/data-module="([^"]+)"/g); if (moduleMatches && moduleMatches.length > 0) { const result = parseByModules(cleanedHTML, platform); if (result.length > 0) return result; } if (platform === 'mailchimp' && cleanedHTML.includes('mc:repeatable')) return parseByMailChimpModules(cleanedHTML); const hasSectionComments = /<!--\s*[A-Z][A-Z\s0-9\-]+\s*STARTS\s*-->/i.test(cleanedHTML); if (hasSectionComments) { const result = parsePennyblackSections(cleanedHTML); if (result && result.length > 0) return result; } return parseByRows(cleanedHTML); };

  // Simplified parseByRows - delegates to the HTML generator
  const parseByRows = (htmlString) => { try { const parser = new DOMParser(); const doc = parser.parseFromString(htmlString, 'text/html'); const mainTable = (() => { const byWidth = Array.from(doc.querySelectorAll('table[width]')).find(t => { const w = parseInt(t.getAttribute('width') || '0'); return w >= 500 && w <= 900; }); if (byWidth) return byWidth; const all = Array.from(doc.querySelectorAll('table')); return all.sort((a, b) => b.querySelectorAll('tr').length - a.querySelectorAll('tr').length)[0] || doc.body; })(); const blocks = []; const processed = new Set(); const rows = mainTable.querySelectorAll(':scope > tbody > tr, :scope > tr'); (rows.length > 0 ? rows : doc.querySelectorAll('tr')).forEach(tr => { if (processed.has(tr)) return; processed.add(tr); const tds = Array.from(tr.querySelectorAll(':scope > td')); if (tds.length === 0) return; if (tds.length >= 2 && tds.length <= 4) { const cols = tds.map(td => { const imgs = Array.from(td.querySelectorAll('img')).filter(i => parseInt(i.getAttribute('width') || '0') > 20 || !i.getAttribute('width')); if (imgs.length === 1) return [{ id: getUniqueId('image'), type: 'image', content: { imageUrl: imgs[0].getAttribute('src') || '', altText: imgs[0].getAttribute('alt') || '', linkUrl: imgs[0].closest('a')?.getAttribute('href') || '', bgColor: 'transparent', bgImageUrl: '', bgSize: 'cover', bgPosition: 'center', padding: 5, borderRadius: 0, width: 100, align: 'center' } }]; const textContent = td.textContent.trim(); if (textContent.length > 2) return [{ id: getUniqueId('text'), type: 'text', content: { text: textContent.substring(0, 500), textColor: '#333333', fontSize: 14, fontWeight: 'normal', align: 'center', bgColor: 'transparent', bgImageUrl: '', bgSize: 'cover', bgPosition: 'center', padding: 10, lineHeight: 1.5, fontFamily: 'Arial, sans-serif' } }]; return []; }); const validCols = cols.filter(c => c.length > 0); if (validCols.length >= 2) blocks.push({ id: getUniqueId('columns'), type: 'columns', content: { colCount: validCols.length, bgColor: 'transparent', bgImageUrl: '', bgSize: 'cover', bgPosition: 'center', padding: 20, align: 'top', cols: validCols } }); } else if (tds.length === 1) { const td = tds[0]; const sub = td.querySelector(':scope > table'); if (sub) { } else { const textContent = td.textContent.trim(); if (textContent.length > 2) blocks.push({ id: getUniqueId('text'), type: 'text', content: { text: textContent.substring(0, 500), textColor: '#333333', fontSize: 14, fontWeight: 'normal', align: 'center', bgColor: 'transparent', bgImageUrl: '', bgSize: 'cover', bgPosition: 'center', padding: 10, lineHeight: 1.5, fontFamily: 'Arial, sans-serif' } }); } } }); return blocks.filter(b => b.type === 'columns' ? !b.content.cols.every(c => c.length === 0) : (b.type === 'text' ? b.content.text.trim().length >= 2 : true)); } catch { return []; } };

  const parseByModules = (htmlString, platform) => { return []; };
  const parsePennyblackSections = (htmlString) => { return null; };
  const parseByMailChimpModules = (htmlString) => { return parseByRows(htmlString); };

  const displayBlocks = previewWithDemo ? applyDemoToBlocks(blocks) : blocks;
  const selInfo = selectedBlockId ? findBlockInfo(blocks, selectedBlockId) : null;
  const selectedBlock = selInfo ? selInfo.block : null;

  const checkEnvatoAndSearch = () => { setLeftPanelTab('envato'); if (envatoResults.length === 0) searchEnvato(envatoQuery); if (!envatoStatus) checkEnvatoStatus(); };

  const onLoadTemplateFromEvent = async (templateId) => {
    if (currentTemplateId && blocks.length > 0) {
      await saveTemplate(templateName || savedTemplates.find(t => t.id === currentTemplateId)?.nombre || 'Plantilla existente', false);
    }
    await handleLoadTemplate(templateId);
  };

  return {
    blocks, setBlocks, settings, setSettings, selectedBlockId, setSelectedBlockId, previewMode, setPreviewMode,
    activeTab, setActiveTab, demoData, setDemoData, previewWithDemo, setPreviewWithDemo, theme, setTheme,
    zipModal, setZipModal, zipFiles, setZipFiles, zipLoading, setZipLoading,
    envatoStatus, setEnvatoStatus, envatoQuery, setEnvatoQuery, envatoResults, setEnvatoResults, envatoLoading, setEnvatoLoading,
    envatoDownloading, setEnvatoDownloading, envatoNeedsSession, setEnvatoNeedsSession, leftPanelTab, setLeftPanelTab,
    isEditingPalette, setIsEditingPalette, editingPaletteId, setEditingPaletteId, paletteForm, setPaletteForm,
    showExportHtml, setShowExportHtml, showSendModal, setShowSendModal, showSettingsModal, setShowSettingsModal,
    settingsTab, setSettingsTab, sendTab, setSendTab, campaignConfig, setCampaignConfig, attachments, setAttachments,
    editingSender, setEditingSender, testingConnection, setTestingConnection, testResult, setTestResult, sendingEmail, setSendingEmail,
    showSaveModal, setShowSaveModal, showTemplatesModal, setShowTemplatesModal, showMediaModal, setShowMediaModal,
    mediaCallbackRef, mediaTab, setMediaTab, templateName, setTemplateName, savedTemplates, setSavedTemplates, copied, setCopied,
    fileInputRef, mediaUploadRef, media, mediaLoading, templatesLoading, palettesLoading, senders,
    currentPalettes, activePalette, displayBlocks, selectedBlock, selInfo,
    findBlockInfo, addBlock, addBlockToSpecificColumn, updateBlockTree, handleUpdateContent, updateSetting,
    removeBlock, moveBlock, duplicateBlock, toggleCreatePalette, startEditPalette, deletePalette, movePalette, applyPalette, savePalette,
    saveTemplate, handleSaveTemplate, handleLoadTemplate, handleNewTemplate, handleOpenSendModal, handleSendCampaign, exportTemplate, handleNetworkUpdate, addNetwork,
    applyDemoData, importTemplate, processZipFile, searchEnvato, downloadEnvatoItem, pasteEnvatoSession, checkEnvatoStatus,
    checkEnvatoAndSearch, detectEnvatoPlatform, importFromHTML, PLATFORM_LABELS_MAP,
    saveAsNew, setSaveAsNew, handleSaveAsNew, handleDeleteTemplate,
    onLoadTemplateFromEvent,
    getTemplate, deleteTemplateFromDb, saveSender, deleteSender, uploadMedia, deleteMedia,
  };
}