/**
 * Seed Template Data v2 — Plantillas mejoradas para Cursos, Leads, Admin,
 * Comunicacion, Seguridad y Documentos.
 *
 * Uso desde el seed principal:
 *   import { getTemplates } from './seed-template-data-v2';
 *   const { cursos, leads, admin, comunicacion, seguridad, documentos } =
 *       getTemplates({ hdr, spac, txt, btn, div, soc, ftr, buildTemplate, defaultNets });
 */

export function getTemplates({ hdr, spac, txt, btn, div, soc, ftr, buildTemplate, defaultNets }: {
  hdr: (logoWidth?: number, bg?: string) => any;
  spac: (h?: number) => any;
  txt: (texto: string, opts?: any) => any;
  btn: (texto: string, url: string, opts?: any) => any;
  div: (color?: string, h?: number) => any;
  soc: (networks: any[], opts?: any) => any;
  ftr: () => any;
  buildTemplate: (nombre: string, evento: string, subject: string, previewText: string, blocks: any[], dark?: boolean) => any;
  defaultNets: any[];
}) {

  // ─── 1. CURSOS & CAPACITACION (10) ──

  const cursos = [
    buildTemplate('Inscripcion a Curso', 'curso_inscripcion_exitosa',
      'Inscrito en {{nombre_curso}}, {{nombre}}',
      'Tu acceso al curso ya esta disponible.',
      [hdr(), spac(20),
        txt('Inscripcion confirmada', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Te has inscrito exitosamente en {{nombre_curso}}. Accede ahora y comienza tu formacion profesional.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Instructor: {{instructor}}  |  Garantia: {{dias_garantia}} dias', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ir al Curso', '{{enlace_curso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¿Dudas? Escribenos al {{whatsapp_soporte}}', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Modulo Liberado', 'curso_modulo_liberado',
      'Nuevo modulo disponible: {{nombre_modulo}}',
      'Un nuevo modulo de {{nombre_curso}} te espera.',
      [hdr(), spac(20),
        txt('Nuevo modulo disponible', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Un nuevo modulo ha sido desbloqueado en tu curso {{nombre_curso}}. Sigue avanzando en tu aprendizaje.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Modulo: {{nombre_modulo}}  |  Avance: {{porcentaje_avance}}%', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Modulo', '{{enlace_curso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¡Sigue asi! Cada modulo te acerca mas a tu certificado.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Recordatorio de Avance', 'curso_recordatorio_avance',
      'Aun tienes {{porcentaje_avance}}% de {{nombre_curso}}',
      'No dejes pasar mas tiempo. ¡Retoma tu curso hoy!',
      [hdr(), spac(20),
        txt('Recordatorio de avance', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Notamos que no has avanzado en tu curso recientemente. No pierdas el impulso y retoma tu formacion.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nProgreso: {{porcentaje_avance}}%\nDias restantes: {{dias_restantes}}\nExpira: {{fecha_expiracion_curso}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Continuar Curso', '{{enlace_curso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¡No pierdas tu inversion! Completa el curso y obten tu certificado.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Curso Completado', 'curso_completado',
      '¡Felicitaciones, {{nombre}}! Completaste {{nombre_curso}}',
      'Has finalizado el curso al 100%. ¡Descarga tu certificado!',
      [hdr(), spac(20),
        txt('Curso completado', { fontSize: 28, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Has completado exitosamente {{nombre_curso}}. Estamos orgullosos de tu dedicacion y compromiso con tu formacion profesional.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Instructor: {{instructor}}  |  Progreso: 100%', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Descargar Certificado', '{{enlace_certificado}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Tambien puedes explorar otros cursos en nuestra plataforma.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Certificado Emitido', 'curso_certificado_emitido',
      'Tu certificado de {{nombre_curso}} esta listo',
      'Descarga tu certificado oficial avalado por Xpand Capital.',
      [hdr(), spac(20),
        txt('Certificado disponible', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Tu certificado oficial ha sido generado y esta disponible para descarga inmediata. Este documento acredita tu formacion profesional.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nInstructor: {{instructor}}\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Certificado', '{{enlace_certificado}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Comparte tu logro en redes sociales y etiqueta a @XpandCapital.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Sesion en Vivo', 'curso_sesion_en_vivo',
      'Sesion en vivo: {{nombre_curso}}',
      '{{fecha_sesion}} a las {{hora_sesion}} con {{instructor}}.',
      [hdr(), spac(20),
        txt('Sesion en vivo', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Te recordamos que tienes una sesion en vivo programada. Preparate para una experiencia de aprendizaje interactiva con tu instructor.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nFecha: {{fecha_sesion}}\nHora: {{hora_sesion}}\nInstructor: {{instructor}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Unirme a la Sesion', '{{enlace_sesion}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Te recomendamos conectarte 5 minutos antes. ¡Te esperamos!', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Evaluacion Disponible', 'curso_evaluacion_disponible',
      'Evaluacion disponible: {{nombre_curso}}',
      'Tu examen de {{nombre_curso}} ya esta habilitado.',
      [hdr(), spac(20),
        txt('Evaluacion disponible', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('La evaluacion de tu curso ya esta disponible. Asegurate de completarla antes de la fecha limite para validar tus conocimientos.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nDisponible hasta: {{fecha_expiracion_curso}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Tomar Evaluacion', '{{enlace_curso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¡Mucho exito en tu evaluacion!', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Evaluacion Calificada', 'curso_evaluacion_calificada',
      'Tu nota de {{nombre_curso}}: {{nota_evaluacion}}/{{nota_maxima}}',
      'Resultados de tu evaluacion ya disponibles.',
      [hdr(), spac(20),
        txt('Resultados de evaluacion', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Tu evaluacion ha sido calificada. Revisa tus resultados y las areas de mejora en la plataforma.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nNota: {{nota_evaluacion}} / {{nota_maxima}}\nInstructor: {{instructor}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Resultados', '{{enlace_curso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Sigue aprendiendo y mejorando. ¡Cada paso cuenta!', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Acceso por Expirar', 'curso_acceso_por_expirar',
      'Tu acceso a {{nombre_curso}} expira en {{dias_restantes}} dias',
      'Aprovecha tu curso antes que expire.',
      [hdr(), spac(20),
        txt('Acceso por expirar', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#f59e0b', paddingTop: 0, paddingBottom: 4 }),
        txt('Tu acceso al curso esta por vencer. ¡No dejes pasar la oportunidad de completarlo y obtener tu certificado!', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nDias restantes: {{dias_restantes}}\nExpira: {{fecha_expiracion_curso}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ir al Curso', '{{enlace_curso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Si necesitas mas tiempo, contacta a soporte al {{whatsapp_soporte}}.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Acceso Expirado', 'curso_acceso_expirado',
      'Tu acceso a {{nombre_curso}} ha expirado',
      'El periodo de acceso al curso ha finalizado.',
      [hdr(), spac(20),
        txt('Acceso expirado', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Tu periodo de acceso al curso {{nombre_curso}} ha finalizado. Si deseas renovar tu acceso o explorar otros cursos, estamos aqui para ayudarte.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Curso: {{nombre_curso}}\nExpiro: {{fecha_expiracion_curso}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Contactanos al {{whatsapp_soporte}} para renovar tu acceso.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),
  ];

  // ─── 2. LEADS & CRM (7) ──

  const leads = [
    buildTemplate('Lead Nuevo', 'lead_nuevo_registrado',
      '¡Gracias por tu interes, {{nombre_lead}}!',
      'Hemos recibido tu solicitud desde {{nombre_campana}}.',
      [hdr(), spac(20),
        txt('Gracias por tu interes', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Hemos recibido tu informacion y pronto un asesor se comunicara contigo para atender tu solicitud de forma personalizada.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Email: {{email_lead}}\nTelefono: {{telefono_lead}}\nCampana: {{nombre_campana}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Mientras tanto, puedes conocer mas sobre nosotros en nuestra web.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Lead Asignado a Asesor', 'lead_asignado_asesor',
      '{{nombre_lead}}, {{nombre_asesor}} sera tu asesor',
      'Tu caso ha sido asignado a un asesor especializado.',
      [hdr(), spac(20),
        txt('Asesor asignado', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Tu solicitud ha sido asignada a un asesor que te atendera de forma personalizada y te guiara en todo el proceso.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Asesor: {{nombre_asesor}}\nEmail: {{email_asesor}}\nWhatsApp: {{whatsapp_asesor}}\nCampana: {{nombre_campana}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('{{nombre_asesor}} se pondra en contacto contigo proximamente.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Lead Contactado', 'lead_contactado',
      '{{nombre_lead}}, gracias por tu tiempo',
      'Fue un placer conversar contigo el {{fecha_contacto}}.',
      [hdr(), spac(20),
        txt('Gracias por tu tiempo', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Gracias por la conversacion que sostuvimos. Valoramos tu tiempo y estamos aqui para resolver cualquier duda adicional que tengas.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Fecha de contacto: {{fecha_contacto}}\nTu asesor: {{nombre_asesor}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Si tienes preguntas, no dudes en escribirnos.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Lead Calificado', 'lead_calificado',
      'Avanzamos contigo, {{nombre_lead}}',
      'Tu perfil ha sido calificado. Pronto te contactaremos.',
      [hdr(), spac(20),
        txt('Perfil calificado', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Hemos avanzado en el proceso y tu perfil ha sido calificado satisfactoriamente. Estamos preparando la siguiente etapa para ti.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Asesor: {{nombre_asesor}}\nEmail: {{email_asesor}}\nWhatsApp: {{whatsapp_asesor}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Pronto recibiras mas informacion sobre los siguientes pasos.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Lead Convertido', 'lead_convertido_cliente',
      '¡Bienvenido a la familia Xpand Capital, {{nombre_lead}}!',
      'Tu proceso de vinculacion ha sido exitoso.',
      [hdr(), spac(20),
        txt('Bienvenido a Xpand Capital', { fontSize: 28, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Estamos felices de darte la bienvenida como nuevo cliente. Tu proceso de vinculacion ha sido exitoso y ya puedes acceder a todos los beneficios.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Tu asesor fue: {{nombre_asesor}}\nEmail: {{email_asesor}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ir al Dashboard', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Estamos comprometidos con tu crecimiento. ¡Bienvenido a bordo!', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Recordatorio Seguimiento', 'lead_recordatorio_seguimiento',
      '{{nombre_lead}}, ¿seguimos conversando?',
      'Hace {{dias_inactivo}} dias que no sabemos de ti.',
      [hdr(), spac(20),
        txt('Seguimos en contacto', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#f59e0b', paddingTop: 0, paddingBottom: 4 }),
        txt('Han pasado {{dias_inactivo}} dias desde nuestro ultimo contacto y queremos saber como vas. ¿Hay algo en lo que podamos ayudarte?', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Tu asesor, {{nombre_asesor}}, esta disponible para ti.\nWhatsApp: {{whatsapp_asesor}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Estaremos encantados de retomar la conversacion cuando gustes.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Lead Perdido', 'lead_perdido',
      'Gracias por tu interes, {{nombre_lead}}',
      'Lamentamos que no hayamos podido concretar en esta ocasion.',
      [hdr(), spac(20),
        txt('Gracias por tu interes', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Lamentamos que no hayamos podido concretar una vinculacion en esta ocasion. Agradecemos el tiempo que compartiste con nosotros.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Asesor: {{nombre_asesor}}\nFecha: {{fecha_contacto}}\nCampana: {{nombre_campana}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Si en el futuro cambias de opinion, estaremos encantados de recibirte.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),
  ];

  // ─── 3. ADMINISTRATIVO (8 - internos, sin redes sociales) ──

  const admin = [
    buildTemplate('Nueva Compra a Revisar', 'admin_nueva_compra_revisar',
      'Compra pendiente de aprobacion: {{nombre_comprador}} {{apellido_comprador}}',
      '{{moneda}} {{total_compra}} via {{metodo_pago_compra}}.',
      [hdr(), spac(20),
        txt('Compra pendiente de aprobacion', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#f59e0b', paddingTop: 0, paddingBottom: 4 }),
        txt('Hay una nueva compra que requiere tu revision. Verifica los detalles y aprueba o rechaza la transaccion.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Comprador: {{nombre_comprador}} {{apellido_comprador}}\nEmail: {{email_comprador}}\nMonto: {{moneda}} {{total_compra}}\nMetodo: {{metodo_pago_compra}}\nFecha: {{fecha_compra}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Revisar Compra', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Accion requerida. Por favor revisa a la brevedad.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Usuario Solicito Baja', 'admin_usuario_solicito_baja',
      'Baja de usuario: {{nombre}} {{apellido}}',
      '{{email}} solicito la baja de su cuenta el {{fecha_solicitud}}.',
      [hdr(), spac(20),
        txt('Usuario solicito baja', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Un usuario ha solicitado la baja de su cuenta. Revisa los detalles y toma la accion correspondiente en el panel de administracion.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Usuario: {{nombre}} {{apellido}}\nEmail: {{email}}\nMotivo: {{motivo_baja}}\nFecha: {{fecha_solicitud}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Panel de Administracion', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Esta solicitud requiere atencion en las proximas 48 horas.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Error Critico del Sistema', 'admin_error_critico',
      'Error critico detectado en el sistema',
      '{{descripcion_error}}',
      [hdr(), spac(20),
        txt('Error critico del sistema', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#dc2626', paddingTop: 0, paddingBottom: 4 }),
        txt('Se ha detectado un error critico en el sistema que requiere atencion inmediata. Revisa los logs y toma accion.', { fontSize: 16, textColor: '#dc2626', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Descripcion: {{descripcion_error}}\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Logs', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Notificacion automatica del sistema. No responder a este correo.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Limite de Usuarios', 'admin_limite_usuarios',
      'Aviso: capacidad de usuarios al {{porcentaje_uso}}%',
      'El plan actual esta cerca de su limite de usuarios.',
      [hdr(), spac(20),
        txt('Limite de usuarios', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#f59e0b', paddingTop: 0, paddingBottom: 4 }),
        txt('El uso de capacidad de usuarios esta llegando al limite del plan actual. Considera ampliar tu plan para evitar interrupciones.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Uso actual: {{porcentaje_uso}}%\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Administrar Plan', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Te recomendamos actuar antes de alcanzar el 100% de capacidad.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Limite de Almacenamiento', 'admin_limite_almacenamiento',
      'Aviso: almacenamiento al {{porcentaje_uso}}%',
      'El espacio de almacenamiento esta casi lleno.',
      [hdr(), spac(20),
        txt('Limite de almacenamiento', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#f59e0b', paddingTop: 0, paddingBottom: 4 }),
        txt('El almacenamiento esta llegando a su capacidad maxima. Libera espacio o amplia tu plan para continuar sin interrupciones.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Uso: {{porcentaje_uso}}%\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Gestionar Almacenamiento', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Puedes eliminar archivos innecesarios o adquirir espacio adicional.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Actividad Sospechosa', 'admin_actividad_sospechosa',
      'Actividad sospechosa detectada: {{nombre}} {{apellido}}',
      'Intento de acceso desde {{ubicacion_sospechosa}}.',
      [hdr(), spac(20),
        txt('Actividad sospechosa detectada', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#dc2626', paddingTop: 0, paddingBottom: 4 }),
        txt('Se ha detectado actividad sospechosa en la plataforma. Revisa los detalles e investiga de inmediato.', { fontSize: 16, textColor: '#dc2626', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Usuario: {{nombre}} {{apellido}}\nEmail: {{email}}\nDispositivo: {{dispositivo_sospechoso}}\nUbicacion: {{ubicacion_sospechosa}}\nHora: {{hora_intento}}\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Investigar', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Se recomienda revision urgente de este caso.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Reporte Mensual', 'admin_reporte_mensual',
      'Reporte mensual disponible: {{fecha_reporte}}',
      'El reporte de {{empresa}} ya esta listo para su revision.',
      [hdr(), spac(20),
        txt('Reporte mensual disponible', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('El reporte mensual ha sido generado y esta listo para su revision. Accede para ver el resumen de actividad y metricas clave.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Empresa: {{empresa}}\nPeriodo: {{fecha_reporte}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Reporte', '{{enlace_reporte}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Los reportes estan disponibles para descarga en formato PDF y Excel.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),

    buildTemplate('Nueva Empresa Registrada', 'admin_nuevo_registro_empresa',
      'Nueva empresa: {{nombre_empresa_nueva}}',
      'Se ha registrado una nueva empresa en la plataforma.',
      [hdr(), spac(20),
        txt('Nueva empresa registrada', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('Una nueva empresa se ha registrado en la plataforma. Revisa los detalles en el panel de superadmin para dar seguimiento.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Empresa: {{nombre_empresa_nueva}}\nEmail: {{email}}\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Panel Superadmin', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('El onboarding inicial debe completarse en las proximas 24 horas.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        ftr(), spac(12)]
    ),
  ];

  // ─── 4. COMUNICACION MASIVA (7) ──

  const comunicacion = [
    buildTemplate('Boletin / Newsletter', 'comunicacion_boletin',
      '{{titulo_boletin}}',
      'Boletin informativo de Xpand Capital — {{fecha_actual}}.',
      [hdr(), spac(20),
        txt('{{titulo_boletin}}', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Te presentamos nuestro boletin informativo con las novedades, articulos y actualizaciones mas relevantes de este periodo.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('[Contenido del boletin — personaliza esta seccion con tus articulos y noticias]\n\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Gracias por ser parte de nuestra comunidad. ¡Hasta el proximo boletin!', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Promocion', 'comunicacion_promocion',
      '{{nombre_promocion}} — Descuento especial para ti',
      '{{porcentaje_descuento}}% de descuento. Codigo: {{codigo_descuento}}.',
      [hdr(), spac(20),
        txt('Oferta especial', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Tenemos una oferta especial para ti. Aprovecha este descuento exclusivo antes de que termine.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Promocion: {{nombre_promocion}}\nDescuento: {{porcentaje_descuento}}%\nCodigo: {{codigo_descuento}}\nValido hasta: {{fecha_expiracion}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Aprovechar Oferta', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¡No dejes pasar esta oportunidad! Cupos limitados.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Anuncio Importante', 'comunicacion_anuncio_importante',
      'Anuncio importante de {{empresa}}',
      'Comunicado oficial — {{fecha_actual}}.',
      [hdr(), spac(20),
        txt('Anuncio importante', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('{{empresa}} tiene un anuncio importante que compartir contigo. A continuacion los detalles del comunicado oficial.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('[Contenido del anuncio — personaliza esta seccion con el comunicado completo]\n\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Agradecemos tu atencion y confianza en {{empresa}}.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Evento Proximo', 'comunicacion_evento_proximo',
      '{{nombre_evento}} — {{fecha_evento}}',
      'Te invitamos a nuestro proximo evento. ¡Reserva tu lugar!',
      [hdr(), spac(20),
        txt('Proximo evento', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Te invitamos a participar en nuestro proximo evento. Sera una experiencia unica de aprendizaje y networking profesional.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Evento: {{nombre_evento}}\nFecha: {{fecha_evento}}\nHora: {{hora_evento}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Registrarme', '{{enlace_evento}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¡Cupos limitados! Reserva tu lugar ahora.', { fontSize: 13, textColor: '#e11d48', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Encuesta', 'comunicacion_encuesta',
      'Ayudanos a mejorar, {{nombre}}',
      'Tu opinion es muy importante para {{empresa}}.',
      [hdr(), spac(20),
        txt('Tu opinion importa', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('En {{empresa}} valoramos tu opinion y queremos seguir mejorando para ti. ¿Nos ayudas respondiendo una breve encuesta?', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Toma menos de 2 minutos.\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Responder Encuesta', '{{enlace_encuesta}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('¡Gracias por ayudarnos a crecer! Tus respuestas son anonimas.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Recordatorio de Cita', 'comunicacion_recordatorio_cita',
      'Recordatorio: cita del {{fecha_cita}} a las {{hora_cita}}',
      'No olvides tu cita programada.',
      [hdr(), spac(20),
        txt('Recordatorio de cita', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Te recordamos tu cita programada. Si necesitas reagendar, contactanos con anticipacion.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Fecha: {{fecha_cita}}\nHora: {{hora_cita}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Detalles', '{{enlace_evento}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Te recomendamos estar listo 5 minutos antes de la hora indicada.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Invitacion a Plataforma', 'comunicacion_invitacion_plataforma',
      '{{nombre}}, te han invitado a {{empresa}}',
      'Unete a la plataforma lider en desarrollo inmobiliario y formacion.',
      [hdr(), spac(20),
        txt('Te han invitado', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Has sido invitado a unirte a {{empresa}}, la plataforma lider en desarrollo inmobiliario y formacion profesional. Crea tu cuenta ahora.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(12),
        btn('Unirme Ahora', '{{enlace_invitacion}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Al unirte obtendras acceso a contenido exclusivo y herramientas profesionales.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),
  ];

  // ─── 5. SEGURIDAD (5) ──

  const seguridad = [
    buildTemplate('2FA Activado', 'seguridad_2fa_activado',
      'Autenticacion en dos pasos activada, {{nombre}}',
      'Tu cuenta ahora es mas segura.',
      [hdr(), spac(20),
        txt('2FA activado', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('La autenticacion en dos pasos (2FA) ha sido activada exitosamente en tu cuenta. Ahora tienes una capa adicional de proteccion.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Fecha: {{fecha_actividad}}\nDispositivo: {{dispositivo}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ir al Dashboard', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Recomendamos mantener 2FA activado para proteger tu informacion.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('2FA Desactivado', 'seguridad_2fa_desactivado',
      '2FA desactivado en tu cuenta, {{nombre}}',
      'La autenticacion en dos pasos ha sido removida.',
      [hdr(), spac(20),
        txt('2FA desactivado', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('La autenticacion en dos pasos (2FA) ha sido desactivada de tu cuenta. Si no realizaste este cambio, contacta a soporte de inmediato.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Fecha: {{fecha_actividad}}\nDispositivo: {{dispositivo}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(16),
        txt('Te recomendamos reactivar 2FA para mantener tu cuenta protegida.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Sesiones Cerradas', 'seguridad_sesiones_cerradas',
      'Todas tus sesiones han sido cerradas, {{nombre}}',
      'Medida de seguridad aplicada a tu cuenta.',
      [hdr(), spac(20),
        txt('Sesiones cerradas', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Por seguridad, todas las sesiones activas de tu cuenta han sido cerradas. Deberas iniciar sesion nuevamente en todos tus dispositivos.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Fecha: {{fecha_actividad}}\nDispositivo: {{dispositivo}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Iniciar Sesion', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Si no realizaste esta accion, cambia tu contrasena de inmediato.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Cambio de Email', 'seguridad_cambio_email',
      'Confirma tu nuevo correo, {{nombre}}',
      'Has solicitado cambiar tu direccion de email.',
      [hdr(), spac(20),
        txt('Confirmacion de cambio de email', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Has solicitado cambiar tu direccion de correo electronico. Para confirmar el cambio, haz clic en el boton de abajo.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Fecha: {{fecha_actividad}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Confirmar Cambio', '{{enlace_confirmar}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Si no realizaste esta solicitud, ignora este mensaje. Tu email actual no sera modificado.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Intento Sospechoso', 'seguridad_intento_sospechoso',
      'Intento de acceso bloqueado, {{nombre}}',
      'Actividad sospechosa detectada en tu cuenta.',
      [hdr(), spac(20),
        txt('Intento de acceso bloqueado', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#dc2626', paddingTop: 0, paddingBottom: 4 }),
        txt('Bloqueamos un intento de acceso sospechoso a tu cuenta. Si no fuiste tu, te recomendamos cambiar tu contrasena de inmediato.', { fontSize: 16, textColor: '#dc2626', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Dispositivo: {{dispositivo_sospechoso}}\nUbicacion: {{ubicacion_sospechosa}}\nHora: {{hora_intento}}\nFecha: {{fecha_actividad}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Cambiar Contrasena', '{{enlace_acceso}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Tu seguridad es nuestra prioridad. Activa 2FA para mayor proteccion.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),
  ];

  // ─── 6. DOCUMENTOS & LEGAL (4) ──

  const documentos = [
    buildTemplate('Contrato Pendiente de Firma', 'documento_contrato_firmar',
      '{{nombre}}, tienes un contrato pendiente de firma',
      '{{nombre_documento}} — {{tipo_contrato}}.',
      [hdr(), spac(20),
        txt('Contrato pendiente de firma', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#e11d48', paddingTop: 0, paddingBottom: 4 }),
        txt('Tienes un documento pendiente de firma. Por favor revisalo detenidamente y firmalo a la brevedad para continuar con el proceso.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Documento: {{nombre_documento}}\nTipo: {{tipo_contrato}}\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Firmar Documento', '{{enlace_documento}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Si tienes dudas sobre el contenido, contacta a tu asesor antes de firmar.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Contrato Firmado', 'documento_contrato_firmado',
      '{{nombre}} {{apellido}} ha firmado {{nombre_documento}}',
      'Documento completado — {{fecha_firma}}.',
      [hdr(), spac(20),
        txt('Contrato firmado', { fontSize: 24, fontWeight: 'bold', align: 'center', textColor: '#059669', paddingTop: 0, paddingBottom: 4 }),
        txt('El documento ha sido firmado exitosamente. Ya esta disponible en el sistema para su consulta y descarga.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Firmante: {{nombre}} {{apellido}}\nEmail: {{email}}\nDocumento: {{nombre_documento}}\nTipo: {{tipo_contrato}}\nFecha de firma: {{fecha_firma}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Documento', '{{enlace_documento}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Guarda una copia del documento para tus registros.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Contrato Vencido', 'documento_contrato_vencido',
      '{{nombre}}, tu {{tipo_contrato}} esta por vencer',
      '{{nombre_documento}} — {{dias_para_vencer}} dias restantes.',
      [hdr(), spac(20),
        txt('Contrato por vencer', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#f59e0b', paddingTop: 0, paddingBottom: 4 }),
        txt('Tu documento esta proximo a vencer. Toma accion antes de la fecha limite para evitar inconvenientes.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Documento: {{nombre_documento}}\nTipo: {{tipo_contrato}}\nVencimiento: {{fecha_vencimiento_contrato}}\nDias restantes: {{dias_para_vencer}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Renovar / Revisar', '{{enlace_documento}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('Te recomendamos actuar con anticipacion para evitar la expiracion.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),

    buildTemplate('Documento Compartido', 'documento_compartido',
      '{{nombre}}, un documento ha sido compartido contigo',
      '{{nombre_documento}} esta disponible para ti.',
      [hdr(), spac(20),
        txt('Documento compartido', { fontSize: 22, fontWeight: 'bold', align: 'center', textColor: '#111827', paddingTop: 0, paddingBottom: 4 }),
        txt('Un documento ha sido compartido contigo. Accede para revisarlo cuando gustes.', { fontSize: 16, textColor: '#4b5563', align: 'center', paddingTop: 0 }),
        spac(8),
        txt('Documento: {{nombre_documento}}\nFecha: {{fecha_actual}}', { fontSize: 14, textColor: '#6b7280', align: 'center' }),
        spac(12),
        btn('Ver Documento', '{{enlace_documento}}', { paddingX: 40, paddingY: 16, fontSize: 16 }),
        spac(16),
        txt('El documento estara disponible en tu panel mientras sea necesario.', { fontSize: 13, textColor: '#9ca3af', align: 'center' }),
        spac(8), div('#e5e7eb'), spac(8),
        soc(defaultNets), spac(8), ftr(), spac(12)]
    ),
  ];

  return { cursos, leads, admin, comunicacion, seguridad, documentos };
}


